import * as fs from "fs";
import * as path from "path";
import type { HardhatRuntimeEnvironment } from "hardhat/types";

export const frontendAbiDir = path.resolve(__dirname, "../../../src/lib/abi");
export const deploymentsDir = path.resolve(__dirname, "../../deployments");

/** The contracts the site talks to and deploys. Mocks are never exported. */
export const EXPORTED = ["Droplock", "HoldsToken", "Cosign"] as const;
export type ExportedName = (typeof EXPORTED)[number];

export type DeploymentRecord = {
  network: string;
  chainId: number;
  deployer: string;
  droplock: string;
  holdsToken: string;
  cosign: string;
  deployedAt: string;
  txHashes: Record<string, string | null>;
};

/**
 * Writes each contract's ABI to ../src/lib/abi/<Name>.abi.json (plain JSON)
 * and <name>Abi.ts (`as const`, so viem and wagmi infer argument and return
 * types), and its creation bytecode to <Name>.bytecode.json. The site deploys the contracts from a
 * wallet through the deterministic deployer, so the bytecode it embeds is
 * what fixes their addresses — one file, shared by the site, the tests and
 * the CLI deploy script.
 */
export async function exportAbis(hre: HardhatRuntimeEnvironment): Promise<void> {
  fs.mkdirSync(frontendAbiDir, { recursive: true });
  for (const name of EXPORTED) {
    const artifact = await hre.artifacts.readArtifact(name);
    const json = JSON.stringify(artifact.abi, null, 2);
    fs.writeFileSync(path.join(frontendAbiDir, `${name}.abi.json`), json + "\n");
    const exportName = name[0].toLowerCase() + name.slice(1) + "Abi";
    const header = "// Generated by contracts/scripts/lib/exportAbi.ts on every `hardhat compile` - do not edit.";
    fs.writeFileSync(path.join(frontendAbiDir, `${exportName}.ts`), `${header}\nexport const ${exportName} = ${json} as const;\n`);
    const build = await hre.artifacts.getBuildInfo(`${artifact.sourceName}:${name}`);
    const record = {
      contractName: name,
      sourceName: artifact.sourceName,
      solcVersion: build?.solcVersion ?? null,
      optimizer: build?.input.settings.optimizer ?? null,
      evmVersion: build?.input.settings.evmVersion ?? null,
      bytecode: artifact.bytecode,
    };
    fs.writeFileSync(path.join(frontendAbiDir, `${name}.bytecode.json`), JSON.stringify(record, null, 2) + "\n");
  }
}
